name: Build and Test
on:
  push:
  pull_request:
    branches:
      - '**'
jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        modules:
          - flink-ml-framework
          - flink-ml-operator
          - flink-ml-tensorflow-common
          - flink-ml-tensorflow
          - flink-ml-tensorflow-2.x
          - flink-ml-pytorch
          - flink-ml-lib
          - flink-ml-examples
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.7'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install Python dependencies
        run: |
          pip install -U --user wheel
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: build
        run: |
          mvn -B install -pl ${{ matrix.modules }} -am -DskipTests -Dfast -Pinstall-py-dep
      - name: test
        env:
          TF_ON_FLINK_IP: 127.0.0.1
        run: |
          mvn -B test -pl ${{ matrix.modules }}
  build-bin:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Bin
        run: |
          mvn -B clean package -pl flink-ml-dist -am -DskipTests -Dfasts
      - name: Upload Bin
        uses: actions/upload-artifact@v2
        with:
          name: flink-ml-bin
          path: flink-ml-dist/target/flink-ml-dist-*-bin
  build-wheels:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.7'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install Python dependencies
        run: |
          python --version
          pip --version
          pip install -U --user wheel
      - name: Build wheels
        run: bash tools/build_wheel.sh
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: tools/dist
